{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zucks",
    "module": "zucks-ad-network-admob-adapter",
    "version": "4.8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yjuupcg7vnflvftfidq5r5o2nu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.6.0"
          }
        },
        {
          "group": "net.zucks",
          "module": "zucks-ad-network-sdk",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "zucks-ad-network-admob-adapter-4.8.4.0.aar",
          "url": "zucks-ad-network-admob-adapter-4.8.4.0.aar",
          "size": 31074,
          "sha512": "3ce17f1c0fe4cfbd5a3fc6bfa554e3bc7cb88a9155b2dfaba909210724cb2eee9b3769860b93842402c53cf55a7ec32f6f24340ec1e12c499222274b8f826fae",
          "sha256": "2e50b23bc6875b7daef2a5063b374ebbbe2783146c0db1fb38b4b3932d5434ac",
          "sha1": "3a0504f13108501479b8935e8f9809441aaf31d9",
          "md5": "0bd73486639f6d73c8adf4cb9df08163"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.zucks",
          "module": "zucks-ad-network-sdk",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "zucks-ad-network-admob-adapter-4.8.4.0.aar",
          "url": "zucks-ad-network-admob-adapter-4.8.4.0.aar",
          "size": 31074,
          "sha512": "3ce17f1c0fe4cfbd5a3fc6bfa554e3bc7cb88a9155b2dfaba909210724cb2eee9b3769860b93842402c53cf55a7ec32f6f24340ec1e12c499222274b8f826fae",
          "sha256": "2e50b23bc6875b7daef2a5063b374ebbbe2783146c0db1fb38b4b3932d5434ac",
          "sha1": "3a0504f13108501479b8935e8f9809441aaf31d9",
          "md5": "0bd73486639f6d73c8adf4cb9df08163"
        }
      ]
    }
  ]
}
