{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zucks.sdk",
    "module": "rewarded-ad",
    "version": "4.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nxoyjshiaffazcv5cut6znxxgq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "net.zucks.sdk",
          "module": "core",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-fragment",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewarded-ad-4.8.4.aar",
          "url": "rewarded-ad-4.8.4.aar",
          "size": 185386,
          "sha512": "e8b15698835a17fa9ab60a4a57706e1c5791945636e579a4b52a17b5dd5e95ee890c54d2063eba471253e895d746bd4afce00eb823b362d085bd432c0e4481f0",
          "sha256": "d6b172f5f15e18eff00f16484de93ef56b000e24c79fac15798b81bfd02c264e",
          "sha1": "2f75e66c71e0c2883edb19435213c396a901efc5",
          "md5": "38d9e066f9d49c80e224956f7ddf09c5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.zucks.sdk",
          "module": "core",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-fragment",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewarded-ad-4.8.4.aar",
          "url": "rewarded-ad-4.8.4.aar",
          "size": 185386,
          "sha512": "e8b15698835a17fa9ab60a4a57706e1c5791945636e579a4b52a17b5dd5e95ee890c54d2063eba471253e895d746bd4afce00eb823b362d085bd432c0e4481f0",
          "sha256": "d6b172f5f15e18eff00f16484de93ef56b000e24c79fac15798b81bfd02c264e",
          "sha1": "2f75e66c71e0c2883edb19435213c396a901efc5",
          "md5": "38d9e066f9d49c80e224956f7ddf09c5"
        }
      ]
    }
  ]
}
