{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zucks.sdk",
    "module": "core",
    "version": "6.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-6.0.1.aar",
          "url": "core-6.0.1.aar",
          "size": 148087,
          "sha512": "95259b8757b714fb34180d19d6a6db1cc57ffdaf66fb951098650bdf1eed7cbc27b4f8a2500ac59ba36da0d9ae6c42b617d214a7c9cccdcdf8e7d1bbda53b6e8",
          "sha256": "71e3182726265fed19bfd4306423ffef33e13214d2b788133dd7ae4d746f8ecc",
          "sha1": "b652bb33eeceaa4a8c239ccfe3c6a1c70054cfee",
          "md5": "e6481e4ebc3c5ffb2273ce2b74c8fc34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-6.0.1.aar",
          "url": "core-6.0.1.aar",
          "size": 148087,
          "sha512": "95259b8757b714fb34180d19d6a6db1cc57ffdaf66fb951098650bdf1eed7cbc27b4f8a2500ac59ba36da0d9ae6c42b617d214a7c9cccdcdf8e7d1bbda53b6e8",
          "sha256": "71e3182726265fed19bfd4306423ffef33e13214d2b788133dd7ae4d746f8ecc",
          "sha1": "b652bb33eeceaa4a8c239ccfe3c6a1c70054cfee",
          "md5": "e6481e4ebc3c5ffb2273ce2b74c8fc34"
        }
      ]
    }
  ]
}
