{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zucks",
    "module": "zucks-ad-network-sdk",
    "version": "4.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "bfwmmh2ncfhtvge2kg3v35a6eq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.zucks.sdk",
          "module": "core",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "net.zucks.sdk",
          "module": "rewarded-ad",
          "version": {
            "requires": "4.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "zucks-ad-network-sdk-4.8.4.aar",
          "url": "zucks-ad-network-sdk-4.8.4.aar",
          "size": 13373,
          "sha512": "dfe154d876e8d9129bf6bf11420eddb28a5b7bc7d49b589b18ce2cd4e1bdcb2d786bbbaa50ad97ac170efc3250abc93350576bb6ac4946004327ebf43b4a8947",
          "sha256": "e9d9b8bd84f464c1a5f8b09e41482beaa7f1be20cb8d385b55c1cc8ac547d30b",
          "sha1": "6b7d49e2cff75ae98624cba9d89099cc0f67b207",
          "md5": "c3ca5803fc5f442ee2e9c155491fe61d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.zucks.sdk",
          "module": "core",
          "version": {
            "requires": "4.8.4"
          }
        },
        {
          "group": "net.zucks.sdk",
          "module": "rewarded-ad",
          "version": {
            "requires": "4.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "zucks-ad-network-sdk-4.8.4.aar",
          "url": "zucks-ad-network-sdk-4.8.4.aar",
          "size": 13373,
          "sha512": "dfe154d876e8d9129bf6bf11420eddb28a5b7bc7d49b589b18ce2cd4e1bdcb2d786bbbaa50ad97ac170efc3250abc93350576bb6ac4946004327ebf43b4a8947",
          "sha256": "e9d9b8bd84f464c1a5f8b09e41482beaa7f1be20cb8d385b55c1cc8ac547d30b",
          "sha1": "6b7d49e2cff75ae98624cba9d89099cc0f67b207",
          "md5": "c3ca5803fc5f442ee2e9c155491fe61d"
        }
      ]
    }
  ]
}
