{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zucks",
    "module": "zucks-ad-network-admob-adapter",
    "version": "6.1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.zucks",
          "module": "zucks-ad-network-sdk",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "zucks-ad-network-admob-adapter-6.1.0.0.aar",
          "url": "zucks-ad-network-admob-adapter-6.1.0.0.aar",
          "size": 43405,
          "sha512": "55bcf4c4ab2be701421b7bfd1867a61c7292fb48a5ec956567906f20fc13323026e79498c74c0defdf7d1665b561e52bd68ca635dc6c1e7ad6d406c0b8448ede",
          "sha256": "7ff9420c47cb8b1345ca7667449de5d44625fa475dc4090ccfd41ff19c6152b0",
          "sha1": "b82fdf8666cf90cc1ad71bf4a6d1a543370a9ae4",
          "md5": "821f4a8ac9d89e9e5fb496a4703f5a6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.zucks",
          "module": "zucks-ad-network-sdk",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "19.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "zucks-ad-network-admob-adapter-6.1.0.0.aar",
          "url": "zucks-ad-network-admob-adapter-6.1.0.0.aar",
          "size": 43405,
          "sha512": "55bcf4c4ab2be701421b7bfd1867a61c7292fb48a5ec956567906f20fc13323026e79498c74c0defdf7d1665b561e52bd68ca635dc6c1e7ad6d406c0b8448ede",
          "sha256": "7ff9420c47cb8b1345ca7667449de5d44625fa475dc4090ccfd41ff19c6152b0",
          "sha1": "b82fdf8666cf90cc1ad71bf4a6d1a543370a9ae4",
          "md5": "821f4a8ac9d89e9e5fb496a4703f5a6b"
        }
      ]
    }
  ]
}
