{
  "formatVersion": "1.1",
  "component": {
    "group": "net.zucks.sdk",
    "module": "rewarded-ad",
    "version": "4.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kb5ckhpxxnamfk57h7wbrgttju"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "net.zucks.sdk",
          "module": "core",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-fragment",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewarded-ad-4.8.3.aar",
          "url": "rewarded-ad-4.8.3.aar",
          "size": 185384,
          "sha512": "90855d68cecf735f6a7d26910bb4066c1654d6d94291b504cc75b6b7f7782d62fd3057caf88de1ba2d2d7390973726495d2db69c86ca69e830ff09f21487facf",
          "sha256": "62ebd7854064d73ff93711f552a52c78734929343d344919e3ad29508023f1bf",
          "sha1": "898a0f9283e89fbca44577fe2afd6c6e1a309e45",
          "md5": "8af4103e74c6c940785b1c977c3d3fd6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.zucks.sdk",
          "module": "core",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-fragment",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewarded-ad-4.8.3.aar",
          "url": "rewarded-ad-4.8.3.aar",
          "size": 185384,
          "sha512": "90855d68cecf735f6a7d26910bb4066c1654d6d94291b504cc75b6b7f7782d62fd3057caf88de1ba2d2d7390973726495d2db69c86ca69e830ff09f21487facf",
          "sha256": "62ebd7854064d73ff93711f552a52c78734929343d344919e3ad29508023f1bf",
          "sha1": "898a0f9283e89fbca44577fe2afd6c6e1a309e45",
          "md5": "8af4103e74c6c940785b1c977c3d3fd6"
        }
      ]
    }
  ]
}
